services:
  db:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    container_name: centro_salud_db
    volumes:
      - ./mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Changed from ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}